### ISSUE TITLE
LBFGS raises Runtime Error

### ISSUE THREAD

**Issue by m-pektas** [owenzlz/Deep_Image_Blending#13]
When I run "run.py" script, I get the following error. **_Error raised from the optimizer_**. How can I solve this. Now, I can running only first stage without solved this issue.

```
Exception has occurred: RuntimeError
view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
  File "../DeepImageBlending/run.py", line 219, in <module>
    optimizer.step(closure)
```

**Comment by samanthawyf** [comment]
Have you solved the problem and how?Thanks!

**Comment by m-pektas** [comment]
No, I couldn't solve it.

**Comment by arcosin** [comment]
I was able to solve this by changing line 171 from:
first_pass_img = torch.from_numpy(first_pass_img).unsqueeze(0).transpose(1,3).transpose(2,3).float().to(gpu_id)
to
first_pass_img = torch.from_numpy(first_pass_img).unsqueeze(0).transpose(1,3).transpose(2,3).contiguous().float().to(gpu_id)

just making that img var contiguous.

**Comment by TheWangYang** [comment]
> 

Oh my God, I solve this problem using this method. Thanks a lot!
