### ISSUE TITLE
RuntimeError after 1st pass

### ISSUE THREAD

**Issue by Md-Ferdous** [owenzlz/Deep_Image_Blending#16]
![image](https://user-images.githubusercontent.com/55968913/190916031-0a8be87e-bda9-4f94-82e2-574b009b30bf.png)

**Comment by NYCXI** [comment]
I meet the same issue, did you fix it?

**Comment by Md-Ferdous** [comment]
No.

**Comment by NYCXI** [comment]
> No.

I have solved this problem via https://github.com/owenzlz/DeepImageBlending/issues/13#issuecomment-986171914

**Comment by Md-Ferdous** [comment]
Thanks a lot, it works
