### ISSUE TITLE
Does this project support high-resolution images?

### ISSUE THREAD

**Issue by ghost** [owenzlz/Deep_Image_Blending#2]

**Comment by owenzlz** [comment]
I have only tested on the images with resolution of 512 or lower. However, it should support higher-resolution with little modifications.

**Comment by abhigoku10** [comment]
@owenzlz  what modifications have to be done for high resoultion images of 2k resolution of target image ? can you please share this

**Comment by RahulBhalley** [comment]
@abhigoku10 I haven't gone through the code but it looks like it's using optimization similar to slow neural style transfer method. If that is the case, then you would optimize for around 2000 steps on 512 scale then upscale it with billinear mode and then further optimize it for 1000 to 2000 steps.
