### ISSUE TITLE
Histogram loss weight

### ISSUE THREAD

**Issue by yijun-li-20** [owenzlz/Deep_Image_Blending#4]
Hi, thank you for your great work and wonderful demo

Here I am confused about whether you choose to use the histogram loss in the implementation. When you have mentioned that in your paper, you didn't have suggested a value for hist_loss weight, just optimizing with other parts of loss function. I am curious if the histogram part is necessary or do you have any advice upon this part of the experiment? Your help is greatly appreciated!

**Comment by owenzlz** [comment]
Hi Sorry for the late reply. Yes, we get rid of the histogram loss for the sake of computation time, since it doesn't help too much.
